### ISSUE TITLE
Password proble

### ISSUE THREAD

**Issue by Netsanetm** [VirusZzHkP/The-Black-Tiger#1]
When it tries to open a browser, its asking for password, which password is it asking, because I tried the system password and it doesn;t work

**Comment by mohamedbassem612** [comment]
+1 on this issue

**Comment by Hsnbacha** [comment]
pass of your OS account like kali user pass

**Comment by Netsanetm** [comment]
> pass of your OS account like kali user pass

Doesn't work

**Comment by VirusZzHkP** [comment]
it's your system's password only
